# Re-export all views from apps for backward compatibility
from apps.accounts.views import (
    CustomTokenObtainPairSerializer,
    CustomTokenObtainPairView,
    RegisterPatientView,
    PatientProfileViewSet,
    MedicalHistoryEntryViewSet,
    PatientDocumentViewSet,
    login_init,
    login_verify,
    forgot_password,
    reset_password,
    verify_reset_otp,
    health_check,
    public_profile,
    generate_qr_code,
    get_qr_token,
    send_otp_email,
)
from apps.contact.views import contact_message_create

__all__ = [
    'CustomTokenObtainPairSerializer',
    'CustomTokenObtainPairView',
    'RegisterPatientView',
    'PatientProfileViewSet',
    'MedicalHistoryEntryViewSet',
    'PatientDocumentViewSet',
    'login_init',
    'login_verify',
    'forgot_password',
    'reset_password',
    'verify_reset_otp',
    'health_check',
    'public_profile',
    'generate_qr_code',
    'get_qr_token',
    'send_otp_email',
    'contact_message_create',
]
