"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from decouple import config


def safe_bool(key, default=False):
    val = config(key, default=None)
    if val is None:
        return default
    if isinstance(val, bool):
        return val
    return str(val).lower() in ('true', '1', 'yes', 'on')


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-cz8s=dxg-wo0%%0eci_2$3sa1lq0vlp5s_!q!+4!6%@_c%)&-)')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = safe_bool('DEBUG', default=True)

ALLOWED_HOSTS = ['localhost', '127.0.0.1', '[::1]', 'digital-health-record-system-2.onrender.com', '.onrender.com']
RENDER_EXTERNAL_HOSTNAME = config('RENDER_EXTERNAL_HOSTNAME', default=None)
if RENDER_EXTERNAL_HOSTNAME and RENDER_EXTERNAL_HOSTNAME not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'apps.accounts',
    'apps.patients',
    'apps.family',
    'apps.medical_history',
    'apps.documents',
    'apps.qr',
    'apps.otp',
    'apps.dashboard',
    'apps.common',
    'apps.contact',
    'core',
]

AUTH_USER_MODEL = 'core.User'

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Use PostgreSQL on Render. Never silently fall back to SQLite in production:
# SQLite lives on Render's ephemeral disk, so all data is lost on every cold
# start / restart (which produced "invalid credentials" after a break).
import dj_database_url
from django.core.exceptions import ImproperlyConfigured

DATABASE_URL = config('DATABASE_URL', default=None)
USE_SQLITE = safe_bool('USE_SQLITE', default=False)
if DATABASE_URL and not USE_SQLITE:
    DATABASES = {
        'default': dj_database_url.config(default=DATABASE_URL, conn_max_age=600),
    }
else:
     DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
    },
}

import os
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom User Model
AUTH_USER_MODEL = 'core.User'

# REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}

# SimpleJWT configuration
from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
}

# CORS — allow the Vite dev server and any localhost port
CORS_ALLOW_ALL_ORIGINS = safe_bool('CORS_ALLOW_ALL_ORIGINS', default=False)
CORS_ALLOW_CREDENTIALS = True

CORS_ALLOWED_ORIGINS = [
    "http://127.0.0.1:5173",
    "http://localhost:5173",
    "https://digital-health-record-system-3.onrender.com",
]
FRONTEND_URL = config('FRONTEND_URL', default='https://digital-health-record-system-3.onrender.com')
if FRONTEND_URL:
    CORS_ALLOWED_ORIGINS.append(FRONTEND_URL)

CSRF_TRUSTED_ORIGINS = [
    "https://digital-health-record-system-3.onrender.com",
    "http://localhost:5173",
    "http://127.0.0.1:5173",
]
if FRONTEND_URL:
    CSRF_TRUSTED_ORIGINS.append(FRONTEND_URL)
if RENDER_EXTERNAL_HOSTNAME:
    CSRF_TRUSTED_ORIGINS.append(f"https://{RENDER_EXTERNAL_HOSTNAME}")

EMAIL_BACKEND = config(
    "EMAIL_BACKEND",
    default="django.core.mail.backends.smtp.EmailBackend"
)

EMAIL_HOST = config("EMAIL_HOST", default="smtp.gmail.com")
EMAIL_PORT = config("EMAIL_PORT", default=587, cast=int)
EMAIL_HOST_USER = config("EMAIL_HOST_USER", default="")
EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD", default="")
EMAIL_USE_TLS = safe_bool("EMAIL_USE_TLS", default=True)
DEFAULT_FROM_EMAIL = config("DEFAULT_FROM_EMAIL", default="")
EMAIL_TIMEOUT = config("EMAIL_TIMEOUT", default=10, cast=int)

GOOGLE_CLIENT_ID = config("GOOGLE_CLIENT_ID", default="")
GOOGLE_CLIENT_SECRET = config("GOOGLE_CLIENT_SECRET", default="")
GOOGLE_REFRESH_TOKEN = config("GOOGLE_REFRESH_TOKEN", default="")

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True

# ──────────────────────────────────────────────────────────────────────────────
# Jazzmin — modern Django Admin UI
# ──────────────────────────────────────────────────────────────────────────────
JAZZMIN_SETTINGS = {
    "site_title": "MeroCare",
    "site_header": "MeroCare",
    "site_brand": "MeroCare",
    "welcome_sign": "MeroCare Administration",
    "copyright": "MeroCare Hospital System",
    "logo": "img/logo.png",
    "login_logo": "img/logo.png",
    "login_logo_dark": "img/logo.png",
    "site_logo": "img/logo.png",
    "site_icon": "img/logo.png",
    "site_logo_classes": "img-circle",
    "show_ui_builder": False,
    "language_chooser": False,
    "hide_apps": [],
    "hide_models": [],
    "order_with_respect_to": [
        "core",
    ],
    "custom_links": {},
    "topmenu_links": [
        {"name": "Dashboard", "url": "/admin/", "icon": "fas fa-tachometer-alt"},
    ],
    "usermenu_links": [
        {"name": "Profile", "url": "/admin/auth/user/", "icon": "fas fa-user"},
        {"name": "Logout", "url": "/admin/logout/", "icon": "fas fa-sign-out-alt"},
    ],
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",
    "related_modal_active": True,
    "theme": "flatly",
    "dark_mode_theme": "darkly",
    "button_classes": {
        "primary": "btn-outline-primary",
        "secondary": "btn-outline-secondary",
        "info": "btn-outline-info",
        "warning": "btn-outline-warning",
        "danger": "btn-outline-danger",
        "success": "btn-outline-success",
    },
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.User": "fas fa-user-md",
        "auth.Group": "fas fa-users",
        "core.User": "fas fa-user-md",
        "core.PatientProfile": "fas fa-hospital-user",
        "core.FamilyMemberProfile": "fas fa-user-friends",
        "core.MedicalHistoryEntry": "fas fa-notes-medical",
        "core.PatientDocument": "fas fa-file-medical",
        "core.PatientOTP": "fas fa-key",
    },
    "dashboard": [
        {
            "type": "stat",
            "value": lambda request: __import__("core.models", fromlist=["User"]).User.objects.count(),
            "name": "Total Users",
            "icon": "fas fa-users",
            "color": "primary",
            "link": "/admin/core/user/",
        },
        {
            "type": "stat",
            "value": lambda request: __import__("core.models", fromlist=["User"]).User.objects.filter(role="PATIENT").count(),
            "name": "Total Patients",
            "icon": "fas fa-hospital-user",
            "color": "info",
            "link": "/admin/core/patientprofile/",
        },
        {
            "type": "stat",
            "value": lambda request: __import__("core.models", fromlist=["User"]).User.objects.filter(role="ADMIN").count(),
            "name": "Total Admins / Hospitals",
            "icon": "fas fa-user-shield",
            "color": "success",
            "link": "/admin/core/user/",
        },
        {
            "type": "stat",
            "value": lambda request: __import__("core.models", fromlist=["FamilyMemberProfile"]).FamilyMemberProfile.objects.count(),
            "name": "Total Family Members",
            "icon": "fas fa-user-friends",
            "color": "warning",
            "link": "/admin/core/familymemberprofile/",
        },
        {
            "type": "stat",
            "value": lambda request: __import__("core.models", fromlist=["PatientProfile"]).PatientProfile.objects.filter(qr_token__isnull=False).count(),
            "name": "QR Generated",
            "icon": "fas fa-qrcode",
            "color": "secondary",
            "link": "/admin/core/patientprofile/",
        },
        {
            "type": "stat",
            "value": lambda request: __import__("core.models", fromlist=["PatientDocument"]).PatientDocument.objects.count(),
            "name": "Documents Uploaded",
            "icon": "fas fa-file-medical",
            "color": "pink",
            "link": "/admin/core/patientdocument/",
        },
        {
            "type": "stat",
            "value": lambda request: __import__("core.models", fromlist=["MedicalHistoryEntry"]).MedicalHistoryEntry.objects.count(),
            "name": "Medical Reports",
            "icon": "fas fa-notes-medical",
            "color": "teal",
            "link": "/admin/core/medicalhistoryentry/",
        },
        {
            "type": "stat",
            "value": lambda request: __import__("core.models", fromlist=["User"]).User.objects.filter(is_active=True).count(),
            "name": "Active Users",
            "icon": "fas fa-user-check",
            "color": "navy",
            "link": "/admin/core/user/",
        },
        {
            "type": "stat",
            "value": lambda request: __import__("core.models", fromlist=["PatientProfile"]).PatientProfile.objects.filter(is_profile_setup=True).count(),
            "name": "Verified Users",
            "icon": "fas fa-check-circle",
            "color": "success",
            "link": "/admin/core/patientprofile/",
        },
        {
            "type": "stat",
            "value": lambda request: __import__("core.models", fromlist=["User"]).User.objects.filter(is_active=False).count(),
            "name": "Pending Requests",
            "icon": "fas fa-clock",
            "color": "danger",
            "link": "/admin/core/user/",
        },
    ],
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": True,
    "brand_small_text": False,
    "brand_colour": "navbar-teal",
    "accent": "accent-teal",
    "navbar": "navbar-light navbar-white border-bottom",
    "sidebar": "sidebar-dark-teal",
    "sidebar_fixed": True,
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "flatly",
    "dark_mode_theme": "darkly",
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-outline-secondary",
        "info": "btn-outline-info",
        "warning": "btn-outline-warning",
        "danger": "btn-danger",
        "success": "btn-outline-success",
    },
    "actions_sticky_top": True,
    "sidebar_nav_width": "260px",
    "navbar_fixed_top": True,
    "layout_boxed": False,
    "footer_fixed": False,
    "side_menu_accordion": False,
    "related_modal_active": True,
}
