# Generated by Django 5.2.4 on 2026-07-09 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_patientprofile_active_prescription_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalreport',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='medicalreport',
            name='patient',
        ),
        migrations.DeleteModel(
            name='InstitutionProfile',
        ),
        migrations.DeleteModel(
            name='MedicalReport',
        ),
    ]
