# Generated by Django 5.2.4 on 2026-07-14 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_medicalreport_institution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymemberprofile',
            name='last_scanned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='familymemberprofile',
            name='scan_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='last_scanned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='scan_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
