# Generated by Django 5.2.4 on 2026-07-21 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_familymemberprofile_last_scanned_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
