# Generated by Django 5.2.4 on 2026-07-22 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_patientdocument_family_member_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='patients',
            field=models.ManyToManyField(blank=True, related_name='assigned_doctors', to='core.patientprofile'),
        ),
    ]
