# Generated by Django 5.2.4 on 2026-07-23 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_doctorprofile_patients'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctorprofile',
            options={},
        ),
        migrations.RemoveField(
            model_name='doctorprofile',
            name='patients',
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='assigned_patients',
            field=models.ManyToManyField(blank=True, related_name='assigned_doctors', to='core.patientprofile'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='availability',
            field=models.TextField(blank=True, help_text='e.g., Mon-Fri 9:00-17:00'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='age',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='department',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='medical_license_number',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='doctor_photos/'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='specialization',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20),
        ),
    ]
